#!/usr/bin/env node
import { spawn } from 'node:child_process';
import { existsSync } from 'node:fs';
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import readline from 'node:readline';
import { pathToFileURL } from 'node:url';

const HOME = process.env.CODEX_HOME || path.join(os.homedir(), '.codex');
const STATE = path.join(HOME, 'persistent-plugin-manager.json');
const PID = path.join(HOME, 'persistent-plugin-manager.pid');
const PORT_FILE = path.join(HOME, 'persistent-plugin-manager.port');
const PORT_MIN = 14000, PORT_MAX = 14100;
const PLUGINS = ['bark-notify', 'cpa-usage', 'task-queue', 'session-importer'];
const names = { 'bark-notify': 'Bark Notify', 'cpa-usage': 'CPA Usage', 'task-queue': 'Task Queue', 'session-importer': 'Session Importer' };

async function ensureHome() { await mkdir(HOME, { recursive: true }); }
async function jsonFile(file, fallback) { try { return JSON.parse(await readFile(file, 'utf8')); } catch { return fallback; } }
async function writeJson(file, value) { await ensureHome(); await writeFile(file, JSON.stringify(value, null, 2) + '\n', 'utf8'); }
// Prefer the working copy, then the newest installed version in the cache.
async function sourceRoot(name) { const direct = path.join(HOME, 'plugins', name); if (existsSync(direct)) return direct; const home = path.join(os.homedir(), 'plugins', name); const cacheDir = path.join(HOME, 'plugins', 'cache', 'personal', name); if (existsSync(cacheDir)) { const versions = (await readdir(cacheDir, { withFileTypes: true })).filter(e => e.isDirectory()).map(e => e.name).sort((a, b) => a.localeCompare(b, undefined, { numeric: true })); if (versions.length > 0) return path.join(cacheDir, versions[versions.length - 1]); } return existsSync(home) ? home : ''; }
async function discover() { const state = await jsonFile(STATE, {}); return Promise.all(PLUGINS.map(async name => ({ name, title: names[name], root: await sourceRoot(name), persistent: name === 'cpa-usage' || name === 'task-queue', enabled: state.workers?.[name]?.enabled !== false, status: 'stopped' }))); }
async function findPort() { for (let p = PORT_MIN; p <= PORT_MAX; p++) { try { const s = http.createServer(); await new Promise((ok, bad) => { s.once('error', bad); s.listen(p, '127.0.0.1', () => s.close(ok)); }); return p; } catch {} } throw new Error('No free port in 14000-14100'); }
async function pluginData(name) {
  if (name === 'bark-notify') { const core = await import(pathToFileURL(path.join(await sourceRoot('bark-notify'), 'scripts', 'bark-core.mjs')).href); const cfg = core.parseConfig(await readFile(path.join(HOME, 'bark-notify.json'), 'utf8').catch(() => '')); return { settings: { mode: cfg.mode, types: cfg.types, templateKeys: core.TEMPLATE_KEYS, levels: core.LEVELS, subscribers: cfg.subscribers.map(s => ({ key: s.key, label: s.label, enabled: s.enabled, profiles: s.profiles })) }, status: { pending: (await jsonFile(path.join(HOME, 'bark-notify-queue.json'), [])).length } }; }
  if (name === 'cpa-usage') { const cfg = await jsonFile(path.join(HOME, 'cpa-usage.json'), {}); return { settings: { baseURL: cfg.baseURL || '', probePath: cfg.probePath || '/models', intervalSeconds: cfg.intervalSeconds || 60, apiKeyConfigured: Boolean(cfg.apiKey) }, status: { worker: 'on-demand' } }; }
  if (name === 'task-queue') { const tasks = await jsonFile(path.join(HOME, 'task-queue.json'), []); const ordered = tasks.slice().sort((a,b) => (b.importance ?? 0) - (a.importance ?? 0) || String(a.updatedAt).localeCompare(String(b.updatedAt))); return { settings: { order: 'importance desc, oldest update first' }, status: { pending: ordered.filter(t => t.status === 'pending').length, tasks: ordered.map(t => ({ id: t.id, title: t.title, status: t.status, importance: t.importance, model: t.model, reasoningEffort: t.reasoningEffort, sessionId: t.sessionId })) } }; }
  const ledger = await jsonFile(path.join(HOME, 'session-importer.json'), {}); return { settings: {}, status: { ledgerEntries: Object.keys(ledger).length } };
}
function applyPush(target, body, levels, withEnabled) { if (withEnabled && body.enabled !== undefined) target.enabled = body.enabled === true; if (body.level !== undefined) { if (!levels.includes(body.level)) throw new Error('Unknown level: ' + body.level); target.level = body.level; } for (const f of ['sound', 'icon', 'group', 'title', 'body']) if (body[f] !== undefined) target[f] = String(body[f]); }
async function updateSettings(name, body) { if (name === 'bark-notify') { const core = await import(pathToFileURL(path.join(await sourceRoot('bark-notify'), 'scripts', 'bark-core.mjs')).href); const file = path.join(HOME, 'bark-notify.json'); const cfg = core.parseConfig(await readFile(file, 'utf8').catch(() => '')); if (body.mode === 'work' || body.mode === 'away') cfg.mode = body.mode; if (body.type && core.TYPE_IDS.includes(body.type)) applyPush(cfg.types[body.type], body, core.LEVELS, true); if (body.profile && core.TYPE_IDS.includes(body.profile)) { const target = cfg.subscribers.find(s => s.key === body.key); if (!target) throw new Error('Unknown subscriber'); if (body.reset === true) delete target.profiles[body.profile]; else { const p = target.profiles[body.profile] || {}; applyPush(p, body, core.LEVELS, true); target.profiles[body.profile] = p; } } if (body.subscriber) { const target = cfg.subscribers.find(s => s.key === body.key); if (!target) throw new Error('Unknown subscriber'); if (body.enabled !== undefined) target.enabled = body.enabled === true; if (body.label !== undefined) target.label = String(body.label).trim() || target.label; } await writeJson(file, { mode: cfg.mode, subscribers: cfg.subscribers, types: cfg.types }); return; } if (name === 'cpa-usage') { const file = path.join(HOME, 'cpa-usage.json'); const cfg = await jsonFile(file, {}); for (const key of ['baseURL', 'probePath', 'intervalSeconds']) if (body[key] !== undefined) cfg[key] = key === 'intervalSeconds' ? Math.max(5, Number(body[key]) || 60) : String(body[key]); await writeJson(file, cfg); return; } throw new Error('This plugin exposes read-only settings in the dashboard'); }
function page(port) { return `<!doctype html><meta name="viewport" content="width=device-width"><title>Personal Plugin Manager</title><style>body{font:15px system-ui;max-width:1050px;margin:30px auto;padding:0 16px;color:#202124}nav{display:flex;gap:8px;flex-wrap:wrap}button{padding:8px 12px;border:1px solid #bbb;border-radius:6px;background:#fff;cursor:pointer}.card{border:1px solid #ddd;border-radius:10px;padding:18px;margin-top:16px}label{display:block;margin:10px 0}input,select,textarea{padding:7px;width:min(480px,100%);font:inherit;box-sizing:border-box}input[type=checkbox]{width:auto}details{border:1px solid #eee;border-radius:8px;padding:8px 12px;margin:8px 0}summary{cursor:pointer}table{border-collapse:collapse;width:100%}td,th{padding:7px;border-bottom:1px solid #eee;text-align:left}.muted{color:#666}</style><h1>Personal Plugin Manager</h1><p class="muted">Local dashboard · port ${port}</p><nav id="nav"></nav><section id="view"></section><script>
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(name){let r=await fetch('/api/plugins/'+name),x=await r.json();document.querySelector('#view').innerHTML=render(name,x);}
function pushFields(p,lv,pre){return '<label>Title template <input name="title" value="'+esc(p.title)+'"'+(pre?' placeholder="inherit"':'')+'></label><label>Body template <textarea name="body" rows="3"'+(pre?' placeholder="inherit"':'')+'>'+esc(p.body)+'</textarea></label><label>Level <select name="level">'+lv.map(l=>'<option '+(p.level===l?'selected':'')+'>'+l+'</option>').join('')+'</select></label><label>Sound <input name="sound" value="'+esc(p.sound)+'"'+(pre?' placeholder="inherit"':'')+'></label><label>Icon URL <input name="icon" value="'+esc(p.icon)+'"'+(pre?' placeholder="inherit"':'')+'></label><label>Group <input name="group" value="'+esc(p.group)+'"'+(pre?' placeholder="inherit"':'')+'></label>'}
function bark(x){const st=x.settings,lv=st.levels;let s='<form onsubmit="save(event,\'bark-notify\')"><label>Focus mode <select name="mode"><option '+(st.mode==='work'?'selected':'')+'>work</option><option '+(st.mode==='away'?'selected':'')+'>away</option></select></label><button>Save mode</button></form><p class="muted">Placeholders: '+st.templateKeys.map(k=>'&lt;'+k+'&gt;').join(', ')+'. Pending in queue: '+x.status.pending+'</p><h3>Notification types</h3>';
for(const id of Object.keys(st.types)){const t=st.types[id];s+='<details><summary>'+esc(id)+' · '+(t.enabled===false?'off':'on')+' · '+esc(t.level)+'</summary><form onsubmit="save(event,\'bark-notify\')"><input type="hidden" name="type" value="'+esc(id)+'"><label><input type="checkbox" name="enabled" '+(t.enabled===false?'':'checked')+'> Enabled</label>'+pushFields(t,lv,false)+'<button>Save type</button></form></details>'}
s+='<h3>Subscribers</h3>';
for(const sub of st.subscribers){s+='<details><summary>'+esc(sub.label)+' · '+(sub.enabled?'enabled':'disabled')+'</summary><form onsubmit="save(event,\'bark-notify\')"><input type="hidden" name="subscriber" value="1"><input type="hidden" name="key" value="'+esc(sub.key)+'"><label>Label <input name="label" value="'+esc(sub.label)+'"></label><label><input type="checkbox" name="enabled" '+(sub.enabled?'checked':'')+'> Receives pushes</label><button>Save subscriber</button></form>';
for(const id of Object.keys(st.types)){const p=sub.profiles[id]||{};const on=p.enabled!==false;s+='<details><summary>'+esc(id)+' profile · '+(Object.keys(p).length?'custom':'inherits')+' · '+(on?'on':'off')+'</summary><form onsubmit="save(event,\'bark-notify\')"><input type="hidden" name="profile" value="'+esc(id)+'"><input type="hidden" name="key" value="'+esc(sub.key)+'"><label><input type="checkbox" name="enabled" '+(on?'checked':'')+'> Send this type to this subscriber</label>'+pushFields({title:p.title||'',body:p.body||'',level:p.level||st.types[id].level,sound:p.sound||'',icon:p.icon||'',group:p.group||''},lv,true)+'<button>Save profile</button> <button type="button" onclick="resetProfile(\''+esc(sub.key)+'\',\''+esc(id)+'\')">Reset to type default</button></form></details>'}
s+='</details>'}
return s}
async function resetProfile(key,id){await fetch('/api/plugins/bark-notify/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({key,profile:id,reset:true})});load('bark-notify')}
function render(n,x){let s='<div class="card"><h2>'+esc(n)+'</h2>';if(n==='bark-notify')s+=bark(x);else if(n==='cpa-usage')s+='<form onsubmit="save(event,\''+n+'\')"><label>Base URL <input name="baseURL" value="'+esc(x.settings.baseURL)+'"></label><label>Probe path <input name="probePath" value="'+esc(x.settings.probePath)+'"></label><label>Interval seconds <input type="number" name="intervalSeconds" min="5" value="'+x.settings.intervalSeconds+'"></label><p>API key: '+(x.settings.apiKeyConfigured?'configured':'not configured')+'</p><button>Save</button></form><p>Worker: '+x.status.worker+'</p>';else if(n==='task-queue'){s+='<p>Ordering: '+esc(x.settings.order)+'</p><table><tr><th>Priority</th><th>Task</th><th>Status</th><th>Model</th><th>Session</th></tr>'+x.status.tasks.map(t=>'<tr><td>'+t.importance+'</td><td>'+esc(t.title)+'</td><td>'+esc(t.status)+'</td><td>'+esc(t.model||'default')+'</td><td>'+esc(t.sessionId)+'</td></tr>').join('')+'</table>';}else s+='<p>Imported ledger entries: '+x.status.ledgerEntries+'</p>';return s+'</div>'}
async function save(e,n){e.preventDefault();let f=new FormData(e.target),b=Object.fromEntries(f);if(n==='cpa-usage')b.intervalSeconds=Number(b.intervalSeconds);if(e.target.querySelector('input[type=checkbox][name=enabled]'))b.enabled=e.target.querySelector('input[type=checkbox][name=enabled]').checked;let r=await fetch('/api/plugins/'+n+'/settings',{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify(b)});if(!r.ok){alert((await r.json()).error);return}load(n)}
fetch('/api/plugins').then(r=>r.json()).then(ps=>{nav.innerHTML=ps.map(p=>'<button onclick="load(\''+p.name+'\')">'+p.title+'</button>').join('');load(ps[0].name)})
</script>`; }
async function dashboard() { const port = await findPort(); await writeFile(PORT_FILE, String(port)); const server = http.createServer(async (req,res) => { try { const url = new URL(req.url, 'http://127.0.0.1'); res.setHeader('x-content-type-options','nosniff'); if (url.pathname === '/api/plugins') { res.setHeader('content-type','application/json'); res.end(JSON.stringify(await discover())); return; } const m = url.pathname.match(/^\/api\/plugins\/([^/]+)(?:\/settings)?$/); if (m && PLUGINS.includes(m[1])) { if (req.method === 'PUT' && url.pathname.endsWith('/settings')) { let raw=''; for await (const c of req) raw += c; await updateSettings(m[1], JSON.parse(raw)); res.end('{}'); return; } res.setHeader('content-type','application/json'); res.end(JSON.stringify(await pluginData(m[1]))); return; } res.setHeader('content-type','text/html; charset=utf-8'); res.end(page(port)); } catch (e) { res.statusCode=400; res.end(JSON.stringify({ error: String(e.message || e) })); } }); await new Promise(resolve => server.listen(port, '127.0.0.1', resolve)); return server; }
async function start() { await ensureHome(); const oldPid = Number((await readFile(PID, 'utf8').catch(() => '0')).trim()); if (oldPid) { try { process.kill(oldPid, 0); return { running: true, pid: oldPid }; } catch {} } const child = spawn(process.execPath, [process.argv[1], '--daemon'], { detached: true, stdio: 'ignore', windowsHide: true }); child.unref(); await writeFile(PID, String(child.pid)); return { running: true, pid: child.pid }; }
async function stop() { try { process.kill(Number((await readFile(PID, 'utf8')).trim())); } catch {} await writeFile(PID, ''); return { stopped: true }; }
async function daemon() { const server = await dashboard(); const shutdown=()=>server.close(()=>process.exit(0)); process.on('SIGTERM',shutdown); process.on('SIGINT',shutdown); }
async function call(name) { if(name==='manager_start')return start(); if(name==='manager_stop')return stop(); if(name==='manager_status')return {dashboard: existsSync(PORT_FILE)?'http://127.0.0.1:'+String((await readFile(PORT_FILE,'utf8')).trim()):null,plugins:await discover()}; if(name==='manager_open')return {url:'http://127.0.0.1:'+String((await readFile(PORT_FILE,'utf8')).trim())}; throw new Error('Unknown tool'); }
if(process.argv[2]==='--daemon')await daemon(); else if(process.argv[2]==='--ensure')await start(); else if(process.argv[2]==='--stop')await stop(); else { await start(); const rl=readline.createInterface({input:process.stdin}); rl.on('line',async line=>{try{const r=JSON.parse(line); if(r.method==='initialize')console.log(JSON.stringify({jsonrpc:'2.0',id:r.id,result:{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'persistent-plugin-manager',version:'0.1.0'}}})); else if(r.method==='tools/list')console.log(JSON.stringify({jsonrpc:'2.0',id:r.id,result:{tools:['manager_start','manager_stop','manager_status','manager_open'].map(name=>({name,description:'Persistent plugin manager control: '+name,inputSchema:{type:'object',properties:{}}}))}})); else if(r.method==='tools/call'){const out=await call(r.params.name);console.log(JSON.stringify({jsonrpc:'2.0',id:r.id,result:{content:[{type:'text',text:JSON.stringify(out)}]}}));}}catch(e){console.log(JSON.stringify({jsonrpc:'2.0',id:0,error:{code:-32000,message:String(e.message||e)}}));}}); }
